# Generated by Django 5.2.10 on 2026-03-21 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_plans', through='workouts.WorkoutPlanExercise', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='exercises.exercise'),
        ),
    ]
