# Generated by Django 5.2.10 on 2026-04-26 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutplan_exercises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutplan',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='userworkoutplan',
            constraint=models.UniqueConstraint(fields=('user', 'day_of_week'), name='unique_day_per_user'),
        ),
    ]
