# Generated by Django 4.2.27 on 2026-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_userworkoutplan_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userworkoutplan',
            name='unique_user_plan',
        ),
        migrations.RemoveConstraint(
            model_name='userworkoutplan',
            name='unique_day_per_user',
        ),
        migrations.AddConstraint(
            model_name='userworkoutplan',
            constraint=models.UniqueConstraint(fields=('user', 'day_of_week', 'workout_plan'), name='unique_workout_per_day_per_user'),
        ),
    ]
