# Generated by Django 5.2.10 on 2026-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemusclegroup',
            name='is_primary',
            field=models.BooleanField(default=True, help_text="Чи є цей м'яз основним для даної вправи?"),
        ),
    ]
