# Generated by Django 5.2.10 on 2026-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercisemusclegroup_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemusclegroup',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Чи є цей м'яз основним для даної вправи?"),
        ),
    ]
