# Generated by Django 4.2.28 on 2026-02-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkoutplan',
            old_name='user_id',
            new_name='user',
        ),
    ]
