# Generated by Django 4.2.27 on 2026-05-15 14:28
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        TrigramExtension()
    ]
