# Generated by Django 4.2.27 on 2026-05-15 14:26

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_normalized',
            field=models.CharField(db_index=True, editable=False, max_length=150),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username_normalized'], name='users_usernam_4fea92_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='user_username_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username_normalized'], name='user_username_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_username_trgm',
        ),
    ]
