version: '3.9'

# name: ${COMPOSE_PROJECT_NAME:-gymbro}

x-django-base: &django_base
  build:
    context: .
    dockerfile: ./Dockerfile
  restart: unless-stopped
  env_file:
    - ./.env
  networks:
    - backend
  depends_on:
    db:
      condition: service_healthy

services:
  web:
    <<: *django_base
    image: gymbro-web
    container_name: web
    volumes:
      - media_data:/app/media
      - .:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  media_data:
  db_data:

networks:
  backend:
    driver: bridge
