# Generated by Django 4.2.27 on 2026-05-11 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bros', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bros',
                'indexes': [models.Index(fields=['sender', 'status'], name='bros_sender__b7cb2d_idx'), models.Index(fields=['receiver', 'status'], name='bros_receive_83c939_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bro',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_bro_relation'),
        ),
        migrations.AddConstraint(
            model_name='bro',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='prevent_self_bro'),
        ),
    ]
