# Generated by Django 4.2.27 on 2026-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bro',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
